name: StatsPlugin
version: 1.0
main: de.deinname.statsplugin.StatsPlugin
api-version: '1.21'
author: DeinName
description: RPG Stats System mit Damage, Crit, Range, Health und Armor

commands:
  stats:
    description: Stats und Level System
    usage: |
      /stats - Zeige deine Stats
      /stats allocate <stat> [amount] - Verteile Skill Points
      /stats resetskills - Setze Skill Points zurück
      /stats set <stat> <wert> [spieler] - Admin
      /stats reset [spieler] - Admin
      /stats save [spieler] - Admin
    permission: stats.use
    permission-message: Du hast keine Berechtigung!
  itemadmin:
    description: Editiere Item-Stats/NBT und Fähigkeiten
    usage:
      /itemadmin <setstat|setability|clear>
    permission: stats.admin


permissions:
  stats.use:
    description: Erlaubt das Anzeigen von Stats
    default: true
  stats.admin:
    description: Erlaubt das Ändern von Stats
    default: op
